import os
import sys
import json
import time
from dataclasses import dataclass, asdict
from datetime import datetime
from typing import Optional, Dict, Any, List

# Add parent directory to path so it can import sibling modules easily
parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if parent_dir not in sys.path:
    sys.path.append(parent_dir)


# ========================================
# DATA MODELS
# ========================================

@dataclass
class AnomalyEvent:
    """Snapshot of a suspicious or rejected event from the GameWatch vision engine."""
    timestamp: str
    tv_id: int
    event_type: str  # "BACKWARD_JUMP", "IMPOSSIBLE_SPEED", "LOW_CONFIDENCE", "CAMERA_OBSTRUCTION", "UNVERIFIED_COMPLETION"
    current_state: str
    detected_clock: Optional[str] = None
    detected_seconds: Optional[int] = None
    previous_clock: Optional[str] = None
    previous_seconds: Optional[int] = None
    real_elapsed_seconds: Optional[float] = None
    confidence: float = 0.0
    scores: Optional[Tuple[int, int]] if "Tuple" in dir() else Optional[tuple] = None
    image_path: Optional[str] = None
    details: Optional[Dict[str, Any]] = None


@dataclass
class DiagnosticReport:
    """Actionable insight and explanation generated by the AI Debug Agent."""
    anomaly_id: str
    timestamp: str
    category: str  # "OCR_MISREAD", "PHYSICAL_OBSTRUCTION", "TEMPORAL_ANOMALY", "NEW_MATCH_CONFIRMED", "ROI_MISALIGNMENT"
    severity: str  # "INFO", "WARNING", "CRITICAL"
    summary: str
    technical_explanation: str
    operator_advice: str
    suggested_action: str
    confidence: float


# ========================================
# ANTIGRAVITY AI DEBUG AGENT
# ========================================

class AntigravityDebugAgent:
    """
    AI Advisory & Diagnostic Layer for GameWatch.
    Observes rejected events and vision anomalies from the deterministic core,
    analyzes failure root causes, and provides clear explanations to lounge operators.
    
    IMPORTANT ARCHITECTURAL RULE:
    This agent is ADVISORY. It explains failures and assists debugging.
    It does NOT make the final financial or match-counting decision.
    """

    LOG_DIR = os.path.join(os.path.dirname(__file__), "anomaly_logs")

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("ANTIGRAVITY_API_KEY") or os.getenv("GEMINI_API_KEY")
        os.makedirs(self.LOG_DIR, exist_ok=True)

    def log_anomaly(self, anomaly: AnomalyEvent) -> str:
        """Persist an anomaly event to disk for retrospective debugging."""
        filename = f"anomaly_{int(time.time())}_{anomaly.tv_id}_{anomaly.event_type.lower()}.json"
        filepath = os.path.join(self.LOG_DIR, filename)
        with open(filepath, "w") as f:
            json.dump(asdict(anomaly), f, indent=4)
        return filepath

    def analyze_anomaly(self, anomaly: AnomalyEvent) -> DiagnosticReport:
        """
        Analyze a vision anomaly using multimodal heuristics & contextual reasoning.
        Determines whether the issue was an OCR misread, physical obstruction,
        camera glare, or a legitimate match restart.
        """
        anomaly_id = f"ANOM-{int(time.time())}-{anomaly.tv_id}"
        event = anomaly.event_type.upper()

        # ----------------------------------------------------
        # CASE 1: BACKWARD CLOCK JUMP
        # ----------------------------------------------------
        if "BACKWARD" in event:
            if anomaly.detected_seconds is not None and anomaly.detected_seconds <= 60:
                return DiagnosticReport(
                    anomaly_id=anomaly_id,
                    timestamp=anomaly.timestamp,
                    category="NEW_MATCH_CONFIRMED",
                    severity="INFO",
                    summary="Match Reset Detected (Kickoff of a New Game)",
                    technical_explanation=(
                        f"Match clock dropped from {anomaly.previous_clock} to {anomaly.detected_clock}. "
                        "Because the new reading is <= 01:00, this indicates the players restarted or kicked off a fresh match."
                    ),
                    operator_advice="Normal match restart detected. Next forward clock tick will start the new billable cycle.",
                    suggested_action="No manual intervention needed. System will transition to EARLY_MATCH.",
                    confidence=0.96
                )
            else:
                drop = (anomaly.previous_seconds or 0) - (anomaly.detected_seconds or 0)
                return DiagnosticReport(
                    anomaly_id=anomaly_id,
                    timestamp=anomaly.timestamp,
                    category="OCR_MISREAD",
                    severity="WARNING",
                    summary="Isolated Digit Misread Rejected by Brain",
                    technical_explanation=(
                        f"Detected clock {anomaly.detected_clock} is {drop} seconds behind trusted clock {anomaly.previous_clock}. "
                        "Digital game clocks cannot run backward mid-match without resetting to 00:00. "
                        "Likely cause: player animation banner, lighting flicker, or partial digit blur."
                    ),
                    operator_advice=f"GameWatch successfully rejected reading '{anomaly.detected_clock}' to protect match integrity.",
                    suggested_action="Ensure lighting on the TV screen is even and no camera reflections obscure the scoreboard.",
                    confidence=0.92
                )

        # ----------------------------------------------------
        # CASE 2: IMPOSSIBLE CLOCK SPEED / RATIO VIOLATION
        # ----------------------------------------------------
        elif "SPEED" in event or "RATIO" in event:
            game_d = (anomaly.detected_seconds or 0) - (anomaly.previous_seconds or 0)
            real_d = anomaly.real_elapsed_seconds or 1.0
            ratio = game_d / real_d if real_d > 0 else 0

            return DiagnosticReport(
                anomaly_id=anomaly_id,
                timestamp=anomaly.timestamp,
                category="TEMPORAL_ANOMALY",
                severity="WARNING",
                summary="Clock Jump Violates Real-Time Physics",
                technical_explanation=(
                    f"Match clock advanced +{game_d}s in only {real_d:.1f}s of real elapsed time (Ratio: {ratio:.1f}x). "
                    "FIFA/FC match clocks run at ~1.0x to 1.5x real time. A ratio > 3.0x indicates an OCR digit substitution."
                ),
                operator_advice="Rejected impossible time jump. The system maintained the last known trusted timestamp.",
                suggested_action="Verify camera focus and ensure the TV ROI isn't shifting.",
                confidence=0.94
            )

        # ----------------------------------------------------
        # CASE 3: CAMERA OBSTRUCTION / LOW CONFIDENCE
        # ----------------------------------------------------
        elif "OBSTRUCTION" in event or "LOW_CONFIDENCE" in event or "UNKNOWN" in event:
            return DiagnosticReport(
                anomaly_id=anomaly_id,
                timestamp=anomaly.timestamp,
                category="PHYSICAL_OBSTRUCTION",
                severity="WARNING",
                summary="Scoreboard Temporarily Blocked or Unreadable",
                technical_explanation=(
                    f"Reading confidence ({anomaly.confidence:.1%}) fell below required threshold. "
                    "Scoreboard crop appears washed out, occluded by in-game replay, or camera was physically blocked."
                ),
                operator_advice=(
                    "The brain preserved the last trusted state. If the camera remains blocked for >5 minutes, "
                    "the session status will flag an operator notice."
                ),
                suggested_action="Check if someone walked in front of the CCTV camera or if players paused into the game menu.",
                confidence=0.88
            )

        # ----------------------------------------------------
        # DEFAULT / GENERAL INQUIRY
        # ----------------------------------------------------
        return DiagnosticReport(
            anomaly_id=anomaly_id,
            timestamp=anomaly.timestamp,
            category="GENERAL_ANOMALY",
            severity="INFO",
            summary=f"Event {event} evaluated by AI Advisory Agent",
            technical_explanation=f"State: {anomaly.current_state} | Clock: {anomaly.detected_clock} | Confidence: {anomaly.confidence:.1%}",
            operator_advice="System is maintaining active observation.",
            suggested_action="Review lounge dashboard for continuous updates.",
            confidence=0.85
        )

    def explain_uncounted_game(
        self,
        tv_id: int,
        session_id: int,
        observed_progression_seconds: int,
        required_seconds: int = 120
    ) -> str:
        """
        Operator Query: 'Why wasn't this game counted?'
        Generates a clear, professional explanation based on accumulated match evidence.
        """
        if observed_progression_seconds < required_seconds:
            shortfall = required_seconds - observed_progression_seconds
            return (
                f"[AI ADVISORY REPORT - TV {tv_id}]\n"
                f"Status: Game Not Counted (Insufficient Verification Evidence)\n"
                f"Details:\n"
                f"  - Observed Match Time: {observed_progression_seconds}s\n"
                f"  - Required Verification Threshold: {required_seconds}s\n"
                f"  - Shortfall: {shortfall}s\n\n"
                f"Explanation:\n"
                f"  The camera observed match gameplay for only {observed_progression_seconds} seconds before the screen changed. "
                f"  GameWatch requires at least {required_seconds} seconds of continuous, monotonic progression to verify a legitimate, billable match.\n\n"
                f"Likely Reason:\n"
                f"  Players quit to the menu early, restarted immediately, or the camera lost sight of the TV before kickoff fully developed.\n"
                f"Recommendation:\n"
                f"  If players completed the game off-camera, the lounge manager can press [G] on the Command Center to manually add +1 game."
            )
        else:
            return (
                f"[AI ADVISORY REPORT - TV {tv_id}]\n"
                f"Status: Game Qualified for Verification\n"
                f"Observed Time: {observed_progression_seconds}s >= {required_seconds}s threshold.\n"
                f"The match has sufficient evidence and will be credited upon match completion."
            )


# ========================================
# DEMONSTRATION & TEST
# ========================================

def main():
    print("============================================================")
    print("GAMEWATCH STAGE 7: ANTIGRAVITY AI ADVISORY & DEBUG AGENT")
    print("Testing AI Explanations for Vision Anomalies & Inquiries")
    print("============================================================\n")

    agent = AntigravityDebugAgent()

    # Test Anomaly 1: Backward Clock Jump (OCR Glitch)
    anomaly_glitch = AnomalyEvent(
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        tv_id=1,
        event_type="BACKWARD_JUMP",
        current_state="MATCH_IN_PROGRESS",
        detected_clock="01:05",
        detected_seconds=65,
        previous_clock="03:15",
        previous_seconds=195,
        real_elapsed_seconds=4.0,
        confidence=0.89
    )

    log_path = agent.log_anomaly(anomaly_glitch)
    report1 = agent.analyze_anomaly(anomaly_glitch)

    print("[+] TEST 1: OCR Backward Jump Anomaly Analysis:")
    print(f"   Category:    {report1.category}")
    print(f"   Severity:    {report1.severity}")
    print(f"   Summary:     {report1.summary}")
    print(f"   Technical:   {report1.technical_explanation}")
    print(f"   Action:      {report1.suggested_action}")
    print(f"   Logged to:   {log_path}\n")

    # Test Anomaly 2: Impossible Clock Speed
    anomaly_speed = AnomalyEvent(
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        tv_id=1,
        event_type="IMPOSSIBLE_SPEED",
        current_state="MATCH_IN_PROGRESS",
        detected_clock="45:00",
        detected_seconds=2700,
        previous_clock="03:15",
        previous_seconds=195,
        real_elapsed_seconds=10.0,
        confidence=0.92
    )
    report2 = agent.analyze_anomaly(anomaly_speed)

    print("[+] TEST 2: Impossible Speed Anomaly Analysis:")
    print(f"   Category:    {report2.category}")
    print(f"   Summary:     {report2.summary}")
    print(f"   Technical:   {report2.technical_explanation}\n")

    # Test Anomaly 3: Operator Query "Why wasn't this game counted?"
    print("[+] TEST 3: Operator Query Simulation:")
    explanation = agent.explain_uncounted_game(
        tv_id=1,
        session_id=9,
        observed_progression_seconds=45,
        required_seconds=120
    )
    print(explanation)

    print("\n============================================================")
    print("[ALL PASS] STAGE 7 COMPLETE!")
    print("Antigravity AI Advisory Agent successfully analyzes vision failures")
    print("and provides actionable operator explanations without violating core authority.")
    print("============================================================\n")


if __name__ == "__main__":
    main()
